---
title: "PG2018 - Conda installation"
date: "June 4, 2018"
---

## Connect to compute node interactively

- This puts you in an environment that can support running programs and doing interactive work.
- **Never, ever run programs on the login node.**

```
srun -p shared -c 1 --mem 1024 -t 120 --pty bash
```

- Your prompt should change from `[username@login-node00 ~]` to 
`[username@compute0000 ~]`.
- **Never, ever run programs if your prompt says `login-node`**.

## Load conda package manager

```
module load anaconda-python/3.6
```

- Add bioconda for scientific software ( [recipes](https://bioconda.github.io/recipes.html#recipes) ).

```
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda
```

## Create environment for an isolated, reproducible software stack

- You will find it useful to keep programs well organized so that you can easily run the version that you need, and avoid conflicting dependencies.  Package managers and software environments do this nicely.

```
conda create --name pg2018
```

## Activate environment

```
source activate pg2018
```

- Now you should see `(pg2018)` before the command line prompt.

## Install programs into this environment

- Copy these lines one at a time and make sure that each installation is successful.

```
conda install macs2=2.1.1.20160309
conda install deeptools=2.5.7
conda install htslib=1.3
conda install rsem=1.3.0
conda install ucsc-wigtobigwig
```

- Now you can run any of these programs from the command line, as long as the pg2018 environment is activated.  Try typing `deeptools` at the command line to make sure that the program is accessible.

## Switch to high performance file system

```
cd ~/scratch
```

## Create working directory

```
mkdir prepwork
cd prepwork
```

## Test deepTools installation

```
computeMatrix reference-point -S ~/work/roadmap/HUES64_rep1.H3K4me3.chr20.bw -R ~/work/genomes/hg19-iGenomes.bed -out k4.mat.gz
plotHeatmap -m k4.mat.gz -o k4.png
```